# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    url: /
    weight: 1
  - name: Projects
    url: projects/
    weight: 2
  - name: Papers
    url: /#papers
    weight: 3
  - name: People
    url: people/
    weight: 4
  - name: News
    url: /#news
    weight: 5
  - name: Software
    url: software/
    weight: 6
  - name: Teaching
    url: teaching/
    weight: 7
  - name: Activities
    url: activities
    weight: 8
 
